Multiplier: 0.25
SetY: 1.0
Subtract: 1
X: 34
Y: 76
Z: 155
SpeedStrength: 2
JumpStrength: 0
bannedwords:
  - Fuck
  - Ass
  - Shit
  - fml
  - bitch
  - whore
  - slut
  - cunt
  - f.u.c.k
  - MothaFucka
  - bish