name: VividNetwork
main: net.vividnetwork.VividNetwork
version: 1.4
authors: [BOBNOTBUILDING, SkylerTyler, xAstraah]

commands:
  Warn:

permission:
  hub.reload: op
  hub.bypass: op
  dropperevent.allowdrop: op
