name: VividNetwork
main: net.vividnetwork.VividNetwork
version: 1.9
authors: [BOBNOTBUILDING, SkylerTyler, xAstraah]

commands:
  Warn:
    description: Warns a player of their action
  stopeffect:
    description: Stops the effects for a player! 

permission:
  vivid.hub.reload: op
  vivid.hub.bypass: op