name: VividNetwork
main: net.vividnetwork.VividNetwork
version: 2.0
authors: [BOBNOTBUILDING, SkylerTyler, xAstraah]

commands:
  Warn:
  StopEffect:

permission:
  vivid.vanishtorch.use:default
  vivid.hub.bypass:op
  vivid.chat.exempt:op
  vivid.allowdrop:op
  vivid.warnings.use: op
